name: "amld"
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - beautifulsoup4=4.10
  - imageio=2.13
  - ipython=7.27
  - jupyter=1.0
  - jupyterlab=3.1
  - matplotlib=3.4
  - nb_conda=2.2
  - nltk=3.6
  - notebook=6.4
  - numpy=1.21
  - pandas=1.3
  - pip=21
  - scikit-learn=1.0
  - scipy=1.7
  - seaborn=0.11
  - tqdm=4
  - pip:
    - tensorflow-hub==0.12
    - tensorflow==2.5
prefix: "/opt/conda"